src/ZLJ.Web.Mvc/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using Abp.AspNetCore.Mvc.Authorization;
using ZLJ.Controllers;

namespace ZLJ.Web.Controllers
{
    [AbpMvcAuthorize]
    public class AboutController : ZLJControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

src/ZLJ.Web.Mvc/Views/Shared/Components/AccountLanguages/AccountLanguagesViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using Abp.Localization;
using Microsoft.AspNetCore.Mvc;

namespace ZLJ.Web.Views.Shared.Components.AccountLanguages
{
    public class AccountLanguagesViewComponent : ZLJViewComponent
    {
        private readonly ILanguageManager _languageManager;

        public AccountLanguagesViewComponent(ILanguageManager languageManager)
        {
            _languageManager = languageManager;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            var model = new LanguageSelectionViewModel
            {
                CurrentLanguage = _languageManager.CurrentLanguage,
                Languages = _languageManager.GetLanguages().Where(l => !l.IsDisabled).ToList()
                .Where(l => !l.IsDisabled)
                .ToList(),
                CurrentUrl = Request.Path
            };

            return Task.FromResult(View(model) as IViewComponentResult);
        }
    }
}

src/ZLJ.Web.Mvc/Views/Shared/Components/RightNavbarLanguageSwitch/RightNavbarLanguageSwitchViewComponent.cs
using System.Linq;
using Abp.Localization;
using Microsoft.AspNetCore.Mvc;

namespace ZLJ.Web.Views.Shared.Components.RightNavbarLanguageSwitch
{
    public class RightNavbarLanguageSwitchViewComponent : ZLJViewComponent
    {
        private readonly ILanguageManager _languageManager;

        public RightNavbarLanguageSwitchViewComponent(ILanguageManager languageManager)
        {
            _languageManager = languageManager;
        }

        public IViewComponentResult Invoke()
        {
            var model = new RightNavbarLanguageSwitchViewModel
            {
                CurrentLanguage = _languageManager.CurrentLanguage,
                Languages = _languageManager.GetLanguages().Where(l => !l.IsDisabled).ToList()
            };

            return View(model);
        }
    }
}

src/ZLJ.Web.Mvc/Views/Shared/Components/RightNavbarUserArea/RightNavbarUserAreaViewComponent.cs
using System.Threading.Tasks;
using Abp.Configuration.Startup;
using ZLJ.Sessions;
using Microsoft.AspNetCore.Mvc;

namespace ZLJ.Web.Views.Shared.Components.RightNavbarUserArea
{
    public class RightNavbarUserAreaViewComponent : ZLJViewComponent
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IMultiTenancyConfig _multiTenancyConfig;

        public RightNavbarUserAreaViewComponent(
            ISessionAppService sessionAppService,
            IMultiTenancyConfig multiTenancyConfig)
        {
            _sessionAppService = sessionAppService;
            _multiTenancyConfig = multiTenancyConfig;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new RightNavbarUserAreaViewModel
            {
                LoginInformations = await _sessionAppService.GetCurrentLoginInformations(),
                IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
            };

            return View(model);
        }
    }
}

src/ZLJ.Web.Mvc/Views/Shared/Components/SideBarMenu/SideBarMenuViewComponent.cs
using System.Threading.Tasks;
using Abp.Application.Navigation;
using Abp.Runtime.Session;
using Microsoft.AspNetCore.Mvc;

namespace ZLJ.Web.Views.Shared.Components.SideBarMenu
{
    public class SideBarMenuViewComponent : ZLJViewComponent
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly IAbpSession _abpSession;

        public SideBarMenuViewComponent(
            IUserNavigationManager userNavigationManager,
            IAbpSession abpSession)
        {
            _userNavigationManager = userNavigationManager;
            _abpSession = abpSession;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new SideBarMenuViewModel
            {
                MainMenu = await _userNavigationManager.GetMenuAsync("MainMenu", _abpSession.ToUserIdentifier())
            };

            return View(model);
        }
    }
}

src/ZLJ.Web.Mvc/Views/Shared/Components/SideBarUserArea/SideBarUserAreaViewComponent.cs
using System.Threading.Tasks;
using Abp.Configuration.Startup;
using ZLJ.Sessions;
using Microsoft.AspNetCore.Mvc;

namespace ZLJ.Web.Views.Shared.Components.SideBarUserArea
{
    public class SideBarUserAreaViewComponent : ZLJViewComponent
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IMultiTenancyConfig _multiTenancyConfig;

        public SideBarUserAreaViewComponent(
            ISessionAppService sessionAppService,
            IMultiTenancyConfig multiTenancyConfig)
        {
            _sessionAppService = sessionAppService;
            _multiTenancyConfig = multiTenancyConfig;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new SideBarUserAreaViewModel
            {
                LoginInformations = await _sessionAppService.GetCurrentLoginInformations(),
                IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
            };

            return View(model);
        }
    }
}

src/ZLJ.Web.Mvc/Views/Shared/Components/TenantChange/TenantChangeViewComponent.cs
using System.Threading.Tasks;
using Abp.ObjectMapping;
using ZLJ.Sessions;
using Microsoft.AspNetCore.Mvc;

namespace ZLJ.Web.Views.Shared.Components.TenantChange
{
    public class TenantChangeViewComponent : ZLJViewComponent
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IObjectMapper _objectMapper;

        public TenantChangeViewComponent(ISessionAppService sessionAppService, IObjectMapper objectMapper)
        {
            _sessionAppService = sessionAppService;
            _objectMapper = objectMapper;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var loginInfo = await _sessionAppService.GetCurrentLoginInformations();
            var model = _objectMapper.Map<TenantChangeViewModel>(loginInfo);
            return View(model);
        }
    }
}

src/ZLJ.Web.Mvc/Views/Shared/Layout/_Alerts.cshtml
@using Abp.Web.Mvc.Alerts

@inject IAlertManager AlertManager

@if (AlertManager.Alerts.Any())
{
    <div class="container-fluid">
        @foreach (var alert in AlertManager.Alerts)
        {
            var alertClass = "alert-";
            var iconClass = "fa-";
            switch (alert.Type)
            {
                case AlertType.Success:
                    alertClass += "success";
                    iconClass += "check";
                    break;
                case AlertType.Danger:
                    alertClass += "danger";
                    iconClass += "ban";
                    break;
                case AlertType.Warning:
                    alertClass += "warning";
                    iconClass += "exclamation-triangle";
                    break;
                case AlertType.Info:
                    alertClass += "info";
                    iconClass += "info";
                    break;
            }

            <div class="alert @alertClass @(alert.Dismissible ? "alert-dismisable" : "") mt-3 mr-1 ml-1">
                @if (alert.Dismissible)
                {
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                }
                <h5>
                    <i class="icon fas @iconClass"></i>
                    @alert.Title
                </h5>
                @alert.Text
            </div>
        }
    </div>
}

src/ZLJ.Web.Mvc/Views/Shared/Layout/_Footer.cshtml
@using ZLJ
<footer class="main-footer">
    <strong>Copyright &copy; @DateTime.Now.Year <a href="javascript:void(0);">ZLJ</a>.</strong> All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>@L("Version")</b> @AppVersionHelper.Version [@AppVersionHelper.ReleaseDate.ToString("yyyyMMdd")]
    </div>
</footer>

src/ZLJ.Web.Mvc/Views/Shared/Layout/_Header.LeftNavbar.cshtml
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="javascript:;"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a class="nav-link" asp-controller="Home" asp-action="Index">@L("HomePage")</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a class="nav-link" asp-controller="About" asp-action="Index">@L("About")</a>
    </li>
</ul>

src/ZLJ.Web.Mvc/Views/Shared/Layout/_Header.RightNavbar.cshtml
@using ZLJ.Web.Views.Shared.Components.RightNavbarLanguageSwitch
@using ZLJ.Web.Views.Shared.Components.RightNavbarUserArea
<ul class="navbar-nav ml-auto">
    @await Component.InvokeAsync(typeof(RightNavbarLanguageSwitchViewComponent))
    @await Component.InvokeAsync(typeof(RightNavbarUserAreaViewComponent))
</ul>

src/ZLJ.Web.Mvc/Views/Shared/Layout/_Header.cshtml
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    @await Html.PartialAsync("_Header.LeftNavbar.cshtml")
    @await Html.PartialAsync("_Header.RightNavbar.cshtml")
</nav>

src/ZLJ.Web.Mvc/Views/Shared/Layout/_Layout.cshtml
@using System.Globalization
@using Abp.Configuration.Startup
@using Abp.Web.Mvc.Alerts
@using Abp.Web.Security.AntiForgery
@using ZLJ.Web.Resources
@inject ZLJ.Timing.AppTimes AppTimes
@inject IAbpAntiForgeryManager AbpAntiForgeryManager
@inject IMultiTenancyConfig MultiTenancyConfig
@inject IWebResourceManager WebResourceManager
@inject IAlertManager AlertManager
@inject ILanguageManager LanguageManager
@{
    AbpAntiForgeryManager.SetCookie(Context);

    var pageTitle = !string.IsNullOrWhiteSpace(ViewBag.Title) ? ViewBag.Title + " / " : "";
    pageTitle += "ZLJ";
}
<!DOCTYPE html>
<html lang="@LanguageManager.CurrentLanguage.Name">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>@pageTitle</title>

    <link rel="shortcut icon" href="~/img/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <environment names="Development">
        <link href="~/libs/font-awesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/libs-ext/famfamfam-flags/dist/sprite/famfamfam-flags.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/libs/animate.css/animate.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/libs/icheck-bootstrap/icheck-bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/libs/toastr/toastr.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/libs/admin-lte/dist/css/adminlte.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/libs/datatables/css/dataTables.bootstrap4.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/libs/datatables/css/responsive.bootstrap4.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/libs/datatables/css/buttons.bootstrap4.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/view-resources/Views/Shared/_Layout.css" rel="stylesheet" asp-append-version="true" />
    </environment>

    <environment names="Staging,Production">
        <link href="~/view-resources/Views/_Bundles/shared-layout.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>

    @RenderSection("styles", required: false)
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        @await Html.PartialAsync("_Header.cshtml")
        @await Html.PartialAsync("_SideBar.cshtml")
        <div class="content-wrapper">
            @await Html.PartialAsync("_Alerts.cshtml")
            @RenderBody()
        </div>
        @await Html.PartialAsync("_Footer.cshtml")
    </div>
    <script type="text/javascript">
        // This is used to get the application's root path from javascript.
        // It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {};
        abp.appPath = '@ApplicationPath';
    </script>
    <environment names="Development">
        <script src="~/libs/jquery/jquery.js" asp-append-version="true"></script>
        <script src="~/libs/bootstrap/dist/js/bootstrap.bundle.js" asp-append-version="true"></script>
        <script src="~/libs/admin-lte/dist/js/adminlte.js" asp-append-version="true"></script>
        <script src="~/libs/jquery-validate/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/libs/jquery-validate/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/libs/block-ui/jquery.blockUI.js" asp-append-version="true"></script>
        <script src="~/libs/spin/spin.js" asp-append-version="true"></script>
        <script src="~/libs-ext/spin/jquery.spin.js" asp-append-version="true"></script>
        <script src="~/libs/sweetalert/sweetalert.min.js" asp-append-version="true"></script>
        <script src="~/libs/toastr/toastr.min.js" asp-append-version="true"></script>
        <script src="~/libs/push.js/push.js" asp-append-version="true"></script>
        <script src="~/libs/moment/moment-with-locales.js" asp-append-version="true"></script>
        <script src="~/libs/abp-web-resources/Abp/Framework/scripts/abp.js" asp-append-version="true"></script>
        <script src="~/libs/abp-web-resources/Abp/Framework/scripts/libs/abp.jquery.js" asp-append-version="true"></script>
        <script src="~/libs/abp-web-resources/Abp/Framework/scripts/libs/abp.toastr.js" asp-append-version="true"></script>
        <script src="~/libs/abp-web-resources/Abp/Framework/scripts/libs/abp.blockUI.js" asp-append-version="true"></script>
        <script src="~/libs/abp-web-resources/Abp/Framework/scripts/libs/abp.spin.js" asp-append-version="true"></script>
        <script src="~/libs/abp-web-resources/Abp/Framework/scripts/libs/abp.sweet-alert.js" asp-append-version="true"></script>
        <script src="~/libs/datatables/js/jquery.dataTables.min.js" asp-append-version="true"></script>
        <script src="~/libs/datatables/js/dataTables.bootstrap4.min.js" asp-append-version="true"></script>
        <script src="~/libs/datatables/js/dataTables.responsive.min.js" asp-append-version="true"></script>
        <script src="~/libs/datatables/js/responsive.bootstrap4.min.js" asp-append-version="true"></script>
        <script src="~/libs/datatables/js/dataTables.buttons.js" asp-append-version="true"></script>
        <script src="~/libs/datatables/js/buttons.bootstrap4.js" asp-append-version="true"></script>
        <script src="~/js/abp.dataTable.js" asp-append-version="true"></script>
        <script src="~/js/main.js" asp-append-version="true"></script>
    </environment>

    <environment names="Staging,Production">
        <script src="~/view-resources/Views/_Bundles/shared-layout.min.js" asp-append-version="true"></script>
    </environment>

    @if (CultureInfo.CurrentUICulture.Name != "en")
    {
        var normalizedCurrentUICultureName = CultureInfo.CurrentUICulture.Name.Replace("-", "_");
        var localizationFileNameWithExtension = "messages_";
        switch (normalizedCurrentUICultureName)
        {
            case "zh_Hans":
                localizationFileNameWithExtension += "zh";
                break;
            case "es_MX":
                localizationFileNameWithExtension += "es";
                break;
            default:
                localizationFileNameWithExtension += normalizedCurrentUICultureName;
                break;
        }
        localizationFileNameWithExtension += ".min.js";
        <script src="~/libs/jquery-validate/localization/@localizationFileNameWithExtension" asp-append-version="true"></script>
    }

    <script type="text/javascript">
        // Localizing momentjs
        moment.locale('@CultureInfo.CurrentUICulture.Name');
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/AbpServiceProxies/GetAll?v=@(AppTimes.StartupTime.Ticks)" type="text/javascript"></script>
    <script src="~/AbpScripts/GetScripts?v=@(AppTimes.StartupTime.Ticks)" type="text/javascript"></script>

    <script src="~/libs/signalr/dist/browser/signalr.js" asp-append-version="true"></script>
    <script src="~/libs/abp-web-resources/Abp/Framework/scripts/libs/abp.signalr-client.js" asp-append-version="true"></script>

    @WebResourceManager.RenderScripts()
    @RenderSection("scripts", required: false)
</body>
</html>

src/ZLJ.Web.Mvc/Views/Shared/Layout/_SideBar.Logo.cshtml
<a class="brand-link" asp-controller="Home" asp-action="Index">
    <img src="~/img/logo.png" alt="Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">ZLJ</span>
</a>

src/ZLJ.Web.Mvc/Views/Shared/Layout/_SideBar.cshtml
@using ZLJ.Web.Views.Shared.Components.SideBarMenu
@using ZLJ.Web.Views.Shared.Components.SideBarUserArea
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    @await Html.PartialAsync("_SideBar.Logo.cshtml")
    <div class="sidebar">
        @await Component.InvokeAsync(typeof(SideBarUserAreaViewComponent))
        @await Component.InvokeAsync(typeof(SideBarMenuViewComponent))
    </div>
</aside>